# Site settings
title: "Ben Casement-Stoll"
logo: logo.jpg # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: kasmander@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aspiring journalist, interested in European politics, economics, America's place in the world, 
  and technology. 
  <br/> Talk to me about your first world problems <a href='http://twitter.com/fonssagrives'>@fonssagrives<a/>. 
url: "http://fonssagrives.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  jekyll

paginate: 5

# Build settings
markdown: kramdown
